version: '3.1'

services:
    db:
        image: postgres:15
        restart: always
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgrespw
            PGDATA: /var/lib/postgresql/data/
        expose:
            - "5432"

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - '8000:8000'
        expose:
            - "8000"
        command: php artisan serve --host=0.0.0.0 --port=8000
        volumes:
            - .:/var/www/html
        depends_on:
            - db

networks:
    snr:

volumes:
    postgres-data:
